### PR TITLE
Bug fix individual surrogate model

### PR DESCRIPTION
**Pull request by harell**
This commit fixes a bug + restructure testthat to follow good practice

### CODE REVIEW

**Comment by harell** [comment]
The subsetting takes variables 1 to 5. This is fine with the HR and apartments datasets, but what about datasets with a different number of columns, say 15?

**Comment by mstaniak** [comment]
> The subsetting takes variables 1 to 5. This is fine with the HR and apartments datasets, but what about datasets with a different number of columns, say 15?

The subset is on observation, not variables.

**Comment by harell** [comment]
True. My mistake.

While it's not a bug, the hard-coded subsetting captured my attention. 

As an unsolicited suggestion, you may want to try head(data$x) for achieving the same thing.

**Comment by mstaniak** [comment]
> As an unsolicited suggestion, you may want to try head(data$x) for achieving the same thing.

Could you please change that in your PR and explain that change in tests? Then I will merge this PR. If you do, please add yourself to the contributors in DESCRIPTION.

**Pull request closed without merging**
